services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    disk:
      name: portfolio-data
      mountPath: /opt/render/project/data
      sizeGB: 1